apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  kustomizeBuildOptions: "--enable-alpha-plugins --enable-exec"
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: XDG_CONFIG_HOME
        value: /.config
      - name: SOPS_AGE_KEY_FILE
        value: /.config/sops/age/key.txt
    volumes:
      - name: custom-tools
        emptyDir: {}
      - name: sops-age-key
        secret:
          secretName: sops-age-key
    initContainers:
      - name: install-ksops
        image: viaductoss/ksops:v4.3.3
        command: ["/bin/sh", "-c"]
        args:
        - 'echo "Installing KSOPS..."; cp ksops /custom-tools/; cp $GOPATH/bin/kustomize /custom-tools/; echo "Done.";'
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    volumeMounts:
      - mountPath: /usr/local/bin/kustomize
        name: custom-tools
        subPath: kustomize
      - mountPath: /usr/local/bin/ksops
        name: custom-tools
        subPath: ksops
      - mountPath: /.config/sops/age/key.txt
        name: sops-age-key
        subPath: key.txt