apiVersion: v1
kind: Namespace
metadata:
    name: arc-runners
    annotations:
        kustomize.config.k8s.io/behavior: merge
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T19:42:39Z"
    mac: ENC[AES256_GCM,data:43rw/WigYbejFI1Sc2DWo8IkNRKqwrIalF72NFY/ouzv+HdjgHLRXNshQWd3MqntsKKnOSA5HmTK8jYZxJ02qGErycbGocOZpyPbaDl7P/sL0fJxaVxB9ichtkSg3G93q3QCe7ytEqj4WzGEBh1lkAV0bQ5XCUJj/LwR1lSaZmc=,iv:XhYi9RvRXCPVmdCQm8wkpAyDC6rrNHuSl4djWeVq8fY=,tag:Kx9CFE22lq+ASY4VygFAzw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: docker-daemon-config
    namespace: arc-runners
    annotations:
        kustomize.config.k8s.io/behavior: merge
data:
    daemon.json:
        mtu: 1400
        default-network-opts:
            bridge:
                com.docker.network.driver.mtu: "1400"
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T19:42:39Z"
    mac: ENC[AES256_GCM,data:43rw/WigYbejFI1Sc2DWo8IkNRKqwrIalF72NFY/ouzv+HdjgHLRXNshQWd3MqntsKKnOSA5HmTK8jYZxJ02qGErycbGocOZpyPbaDl7P/sL0fJxaVxB9ichtkSg3G93q3QCe7ytEqj4WzGEBh1lkAV0bQ5XCUJj/LwR1lSaZmc=,iv:XhYi9RvRXCPVmdCQm8wkpAyDC6rrNHuSl4djWeVq8fY=,tag:Kx9CFE22lq+ASY4VygFAzw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: arc-runner-set
    namespace: openshift-gitops
    annotations:
        kustomize.config.k8s.io/behavior: replace
spec:
    syncPolicy:
        automated:
            prune: false
            selfHeal: true
    project: default
    source:
        chart: gha-runner-scale-set
        repoURL: ghcr.io/actions/actions-runner-controller-charts
        targetRevision: 0.11.0
        helm:
            releaseName: arc
            valuesObject:
                githubConfigUrl: https://github.com/makeitworkcloud
                githubConfigSecret:
                    github_token: ENC[AES256_GCM,data:fIRx5SaP1JKyJRclltYuuZgZ7H34kx6HwubWyggbBuVbem0jSADXtw==,iv:KcKMld41/Nyt1IX0dxwWYVjEpLJXEX5l4ctD4Hshdmg=,tag:iO9KoV28YtawRjnEA88ynw==,type:str]
                controllerServiceAccount:
                    namespace: arc-systems
                    name: arc-gha-rs-controller
                template:
                    spec:
                        initContainers:
                            - name: init-dind-externals
                              image: ghcr.io/actions/actions-runner:latest
                              command:
                                - cp
                                - -r
                                - -v
                                - /home/runner/externals/.
                                - /home/runner/tmpDir/
                              volumeMounts:
                                - name: dind-externals
                                  mountPath: /home/runner/tmpDir
                            - name: init-dind-rootless
                              image: docker:dind-rootless
                              command:
                                - sudo
                                - sh
                                - -c
                                - |
                                  set -x
                                  cp -a /etc/. /dind-etc/
                                  echo 'runner:x:1001:1001:runner:/home/runner:/bin/ash' >> /dind-etc/passwd
                                  echo 'runner:x:1001:' >> /dind-etc/group
                                  echo 'runner:100000:65536' >> /dind-etc/subgid
                                  echo 'runner:100000:65536' >> /dind-etc/subuid
                                  chmod 755 /dind-etc;
                                  chmod u=rwx,g=rx+s,o=rx /dind-home
                                  chown 1001:1001 /dind-home
                              securityContext:
                                allowPrivilegeEscalation: true
                                capabilities:
                                    drop:
                                        - ALL
                                runAsNonRoot: true
                                runAsUser: 1001
                                runAsGroup: 123
                              volumeMounts:
                                - mountPath: /dind-etc
                                  name: dind-etc
                                - mountPath: /dind-home
                                  name: dind-home
                        containers:
                            - name: runner
                              image: ghcr.io/actions/actions-runner:latest
                              command:
                                - /home/runner/run.sh
                              securityContext:
                                allowPrivilegeEscalation: false
                                capabilities:
                                    drop:
                                        - ALL
                                runAsNonRoot: true
                                runAsUser: 1001
                                runAsGroup: 123
                              env:
                                - name: DOCKER_HOST
                                  value: unix:///var/run/docker.sock
                              volumeMounts:
                                - name: work
                                  mountPath: /home/runner/_work
                                - name: dind-sock
                                  mountPath: /var/run
                            - name: dind
                              image: docker:dind-rootless
                              args:
                                - dockerd
                                - --host=unix:///var/run/docker.sock
                                - --group=$(DOCKER_GROUP_GID)
                              env:
                                - name: DOCKER_GROUP_GID
                                  value: "123"
                              securityContext:
                                privileged: true
                                capabilities:
                                    drop:
                                        - ALL
                                runAsNonRoot: true
                                runAsUser: 1001
                                runAsGroup: 123
                              volumeMounts:
                                - name: work
                                  mountPath: /home/runner/_work
                                - name: var-lib-docker
                                  mountPath: /var/lib/docker
                                - name: dind-sock
                                  mountPath: /var/run
                                - name: dind-externals
                                  mountPath: /home/runner/externals
                                - mountPath: /etc/docker/daemon.json
                                  name: daemon-json
                                  readOnly: true
                                  subPath: daemon.json
                        volumes:
                            - name: work
                              emptyDir: {}
                            - name: var-lib-docker
                              ephemeral:
                                volumeClaimTemplate:
                                    spec:
                                        accessModes:
                                            - ReadWriteOnce
                                        resources:
                                            requests:
                                                storage: 50Gi
                            - name: dind-sock
                              emptyDir: {}
                            - name: dind-externals
                              emptyDir: {}
                            - configMap:
                                name: docker-daemon-config
                              name: daemon-json
                            - name: dind-etc
                              emptyDir: {}
                            - name: dind-home
                              emptyDir: {}
    destination:
        server: https://kubernetes.default.svc
        namespace: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T19:42:39Z"
    mac: ENC[AES256_GCM,data:43rw/WigYbejFI1Sc2DWo8IkNRKqwrIalF72NFY/ouzv+HdjgHLRXNshQWd3MqntsKKnOSA5HmTK8jYZxJ02qGErycbGocOZpyPbaDl7P/sL0fJxaVxB9ichtkSg3G93q3QCe7ytEqj4WzGEBh1lkAV0bQ5XCUJj/LwR1lSaZmc=,iv:XhYi9RvRXCPVmdCQm8wkpAyDC6rrNHuSl4djWeVq8fY=,tag:Kx9CFE22lq+ASY4VygFAzw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: arc-runners-scc-rb
    namespace: arc-runners
    annotations:
        kustomize.config.k8s.io/behavior: merge
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:github-arc
subjects:
    - kind: ServiceAccount
      name: arc-gha-rs-no-permission
      namespace: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T19:42:39Z"
    mac: ENC[AES256_GCM,data:43rw/WigYbejFI1Sc2DWo8IkNRKqwrIalF72NFY/ouzv+HdjgHLRXNshQWd3MqntsKKnOSA5HmTK8jYZxJ02qGErycbGocOZpyPbaDl7P/sL0fJxaVxB9ichtkSg3G93q3QCe7ytEqj4WzGEBh1lkAV0bQ5XCUJj/LwR1lSaZmc=,iv:XhYi9RvRXCPVmdCQm8wkpAyDC6rrNHuSl4djWeVq8fY=,tag:Kx9CFE22lq+ASY4VygFAzw==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
