---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-dind-runners
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: arc-dind
  namespace: arc-dind-runners
spec:
  replicas: 1
  dockerdWithinRunnerContainer: true
  ephemeral: false
  organization: makeitworkcloud
