apiVersion: v1
kind: Namespace
metadata:
    name: arc-dind-systems
    annotations:
        kustomize.config.k8s.io/behavior: merge
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSkxiUjNPcVkvaVY4NEV4
            Ulh4UmJJNnFlZ1kvZGtqVHhSWHdjSWJuVGxnClZzcWFTVEJGOFpsL1hVcnVyd1B2
            NzVRUDZBU0tXeHBFdEFKZ25ic0k2RGsKLS0tIDJQZXphSC9KcitGK3MwSUJ1Ylds
            T3dha3hXTEE3Q2xLRGxEZFFCdnREU2sK2gqg8WPDdCPEbFaxDwMjteIT51vRI9JJ
            HxvKEEmNasazh+vSecF7W+lJfSeLEisdtqfchPT8XPy7avDlHp0MPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T05:01:01Z"
    mac: ENC[AES256_GCM,data:lkxHu02PvtanGSWbp/i+KN095YVIK2ECQGAwMq8PFmLimnrxG5CKP2eTzulbAllEovOrJg09zVaU75CkZdL2KZebJouOJAX06rNwmcr2X7lQ9mmkH/nSg2NcNFt/svoXrgAhX88dmf46up3/NUZitSpmuGXQUGVTpUmctcrRy3Q=,iv:8Col2GH6E1bay2c+YNVQlMty3FlrfoS0e2A9FHtFZ58=,tag:3v+47S1C9X8s13OCUWEidg==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: arc-dind
    namespace: openshift-gitops
    annotations:
        kustomize.config.k8s.io/behavior: merge
spec:
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - ServerSideApply=true
    project: default
    source:
        chart: actions-runner-controller
        repoURL: actions-runner-controller.github.io/actions-runner-controller
        targetRevision: 0.22.0
        helm:
            releaseName: arc-dind
            valuesObject:
                authSecret:
                    github_token: ENC[AES256_GCM,data:SIyjPbMN3EaWoJKL2E6uomo5QMx0mQa2dhUYYXhdkjADrylRemtN3w==,iv:dsff2qtJXDdX/PEgXi0zdZiU9u9Q6n7QR5Vl5n2LDYI=,tag:xHvHdEuw6rTaSkqGDC0rpQ==,type:str]
    destination:
        server: https://kubernetes.default.svc
        namespace: arc-dind-systems
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSkxiUjNPcVkvaVY4NEV4
            Ulh4UmJJNnFlZ1kvZGtqVHhSWHdjSWJuVGxnClZzcWFTVEJGOFpsL1hVcnVyd1B2
            NzVRUDZBU0tXeHBFdEFKZ25ic0k2RGsKLS0tIDJQZXphSC9KcitGK3MwSUJ1Ylds
            T3dha3hXTEE3Q2xLRGxEZFFCdnREU2sK2gqg8WPDdCPEbFaxDwMjteIT51vRI9JJ
            HxvKEEmNasazh+vSecF7W+lJfSeLEisdtqfchPT8XPy7avDlHp0MPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T05:01:01Z"
    mac: ENC[AES256_GCM,data:lkxHu02PvtanGSWbp/i+KN095YVIK2ECQGAwMq8PFmLimnrxG5CKP2eTzulbAllEovOrJg09zVaU75CkZdL2KZebJouOJAX06rNwmcr2X7lQ9mmkH/nSg2NcNFt/svoXrgAhX88dmf46up3/NUZitSpmuGXQUGVTpUmctcrRy3Q=,iv:8Col2GH6E1bay2c+YNVQlMty3FlrfoS0e2A9FHtFZ58=,tag:3v+47S1C9X8s13OCUWEidg==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
