---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-dind-runners
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: docker-daemon-config
    namespace: arc-dind-runners
    annotations:
        kustomize.config.k8s.io/behavior: merge
data:
    daemon.json: '{"insecure-registries": ["image-registry.openshift-image-registry.svc:5000", "image-registry.openshift-image-registry.svc.cluster.local:5000", "10.217.5.181:5000", "default-route-openshift-image-registry.apps.makeitwork.cloud"]}'
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-dind
  namespace: arc-dind-runners
spec:
  replicas: 1
  template:
    spec:
      image: summerwind/actions-runner-dind
      ephemeral: false
      dockerdWithinRunnerContainer: true
      organization: makeitworkcloud
      labels:
        - arc-dind
      volumeMounts:
        - mountPath: /home/runner/.config/docker/daemon.json
          name: daemon-config-volume
          subPath: daemon.json
      volumes:
        - name: daemon-config-volume
          configMap:
            name: docker-daemon-config
            items:
              - key: daemon.json
                path: daemon.json
