apiVersion: v1
kind: Namespace
metadata:
    name: arc-dind-systems
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSkxiUjNPcVkvaVY4NEV4
            Ulh4UmJJNnFlZ1kvZGtqVHhSWHdjSWJuVGxnClZzcWFTVEJGOFpsL1hVcnVyd1B2
            NzVRUDZBU0tXeHBFdEFKZ25ic0k2RGsKLS0tIDJQZXphSC9KcitGK3MwSUJ1Ylds
            T3dha3hXTEE3Q2xLRGxEZFFCdnREU2sK2gqg8WPDdCPEbFaxDwMjteIT51vRI9JJ
            HxvKEEmNasazh+vSecF7W+lJfSeLEisdtqfchPT8XPy7avDlHp0MPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T04:59:16Z"
    mac: ENC[AES256_GCM,data:DOIABAlJOhzDNZ8YAWZdjKLVTFKSdo43y6V5SlAyRkVpFEq/bYw3O6fLAp9kVZ+uzYmpBx+LOZOCVISOmd/q/dYfkyaLwVcZhroik+xaJklUcnnf/ndjaV4lMQjNZYpn70iHcPKtXOOlgzmtlmLX8GnpKghcQVSQewKtH5Nuays=,iv:So/UUTh3iJzNG0R4Iply/8lTLhD5qaBxUNPWBLVGpNI=,tag:hysuTm0AJZ8cdFcUCKQpjQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: arc-dind
    namespace: openshift-gitops
spec:
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - ServerSideApply=true
    project: default
    source:
        chart: actions-runner-controller
        repoURL: actions-runner-controller.github.io/actions-runner-controller
        targetRevision: 0.22.0
        helm:
            releaseName: arc-dind
            valuesObject:
                authSecret:
                    github_token: ENC[AES256_GCM,data:SIyjPbMN3EaWoJKL2E6uomo5QMx0mQa2dhUYYXhdkjADrylRemtN3w==,iv:dsff2qtJXDdX/PEgXi0zdZiU9u9Q6n7QR5Vl5n2LDYI=,tag:xHvHdEuw6rTaSkqGDC0rpQ==,type:str]
    destination:
        server: https://kubernetes.default.svc
        namespace: arc-dind-systems
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSkxiUjNPcVkvaVY4NEV4
            Ulh4UmJJNnFlZ1kvZGtqVHhSWHdjSWJuVGxnClZzcWFTVEJGOFpsL1hVcnVyd1B2
            NzVRUDZBU0tXeHBFdEFKZ25ic0k2RGsKLS0tIDJQZXphSC9KcitGK3MwSUJ1Ylds
            T3dha3hXTEE3Q2xLRGxEZFFCdnREU2sK2gqg8WPDdCPEbFaxDwMjteIT51vRI9JJ
            HxvKEEmNasazh+vSecF7W+lJfSeLEisdtqfchPT8XPy7avDlHp0MPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T04:59:16Z"
    mac: ENC[AES256_GCM,data:DOIABAlJOhzDNZ8YAWZdjKLVTFKSdo43y6V5SlAyRkVpFEq/bYw3O6fLAp9kVZ+uzYmpBx+LOZOCVISOmd/q/dYfkyaLwVcZhroik+xaJklUcnnf/ndjaV4lMQjNZYpn70iHcPKtXOOlgzmtlmLX8GnpKghcQVSQewKtH5Nuays=,iv:So/UUTh3iJzNG0R4Iply/8lTLhD5qaBxUNPWBLVGpNI=,tag:hysuTm0AJZ8cdFcUCKQpjQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
