---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ansible
- devspaces
- arc
patches:
- path: overlays/argocd.yaml
  target:
    kind: ArgoCD
    name: openshift-gitops
generators:
- generator
