---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: controller
  namespace: aap
  annotations:
     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  projects_storage_size: 20Gi
  auto_upgrade: true
  projects_storage_access_mode: ReadWriteMany
  projects_persistence: true
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  task_liveness_timeout: 1
  admin_email: steven@makeitwork.cloud
  route_host: ansible.makeitwork.cloud
  route_tls_secret: makeitwork-tls
  projects_use_existing_claim: _No_
