---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: aap
---
apiVersion: v1
kind: Namespace
metadata:
  name: aap
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform-operator
  namespace: aap
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform-operator-tf
  namespace: aap
spec:
  channel: stable-2.5
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
