apiVersion: v1
kind: Namespace
metadata:
    name: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T07:26:30Z"
    mac: ENC[AES256_GCM,data:ML9JJnI/QoXmwFGPHfHWR7hT7Jvs/4NohrhdTLasFd/3hBJM/4CfhNWJFBxCs3jbtCC8+re6xOygbLnHy5dkdnsVOzuPtIMXTG0e+H05dnoZd1ruBRf95Nb7e69WK0Z+TVSlYHVx6IbP4EB6HwxS/5erddNaSzFhGwcMsy317cU=,iv:Gzqi9Z5TOx7/VhOmL9cUepT3r65MfJDb6dhLqu7iUDY=,tag:GpoGVYpMD/oWKGyvZxAoXQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: arc-runner-set
    namespace: openshift-gitops
    annotations:
        kustomize.config.k8s.io/behavior: merge
spec:
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
    project: default
    source:
        chart: gha-runner-scale-set
        repoURL: ghcr.io/actions/actions-runner-controller-charts
        targetRevision: 0.11.0
        helm:
            releaseName: arc-runner-set
            valuesObject:
                githubConfigUrl: https://github.com/makeitworkcloud
                githubConfigSecret:
                    github_token: ENC[AES256_GCM,data:fIRx5SaP1JKyJRclltYuuZgZ7H34kx6HwubWyggbBuVbem0jSADXtw==,iv:KcKMld41/Nyt1IX0dxwWYVjEpLJXEX5l4ctD4Hshdmg=,tag:iO9KoV28YtawRjnEA88ynw==,type:str]
                controllerServiceAccount:
                    namespace: arc-systems
                    name: arc-gha-rs-controller
                template:
                    spec:
                        containers:
                            - name: runner
                              image: ghcr.io/actions/actions-runner:latest
                              command:
                                - /home/runner/run.sh
                              securityContext:
                                allowPrivilegeEscalation: false
                                capabilities:
                                    drop:
                                        - ALL
                                runAsNonRoot: true
                                runAsUser: 1001
                                runAsGroup: 123
    destination:
        server: https://kubernetes.default.svc
        namespace: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T07:26:30Z"
    mac: ENC[AES256_GCM,data:ML9JJnI/QoXmwFGPHfHWR7hT7Jvs/4NohrhdTLasFd/3hBJM/4CfhNWJFBxCs3jbtCC8+re6xOygbLnHy5dkdnsVOzuPtIMXTG0e+H05dnoZd1ruBRf95Nb7e69WK0Z+TVSlYHVx6IbP4EB6HwxS/5erddNaSzFhGwcMsy317cU=,iv:Gzqi9Z5TOx7/VhOmL9cUepT3r65MfJDb6dhLqu7iUDY=,tag:GpoGVYpMD/oWKGyvZxAoXQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: arc-runners-scc-rb
    namespace: arc-runners
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:openshift:scc:github-arc
subjects:
    - kind: ServiceAccount
      name: arc-runner-set-gha-rs-no-permission
      namespace: arc-runners
sops:
    age:
        - recipient: age152ek83tm4fj5u70r3fecytn4kg7c5xca24erjchxexx4pfqg6das7q763l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDBJM0F3em1tVCtKNTdy
            MENEYk52K2dRQ0p6ZHFCYXNidktFOGdadzFjCmhUWG5BTE8wWFltYTdzT1hIZmY2
            MHM1ejA0ckdFUVZjWWYxU0pXMzNVZVkKLS0tIHVqSEo4MStKL0tjSHdhTXFBcjFO
            L1dVQW9WODBGWUpvL00xWE9hK1B1SFUKY7y80019V+3Hg3xi3nMHp32dwh32D28i
            5ErMl32hZ9uYsyofHANDg+I9GAHleo9FoksMh4GHNX3IT4LepgQSMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T07:26:30Z"
    mac: ENC[AES256_GCM,data:ML9JJnI/QoXmwFGPHfHWR7hT7Jvs/4NohrhdTLasFd/3hBJM/4CfhNWJFBxCs3jbtCC8+re6xOygbLnHy5dkdnsVOzuPtIMXTG0e+H05dnoZd1ruBRf95Nb7e69WK0Z+TVSlYHVx6IbP4EB6HwxS/5erddNaSzFhGwcMsy317cU=,iv:Gzqi9Z5TOx7/VhOmL9cUepT3r65MfJDb6dhLqu7iUDY=,tag:GpoGVYpMD/oWKGyvZxAoXQ==,type:str]
    encrypted_regex: ^(github_token)$
    version: 3.10.2
