---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: openshift-gitops
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.11.0
    helm:
      releaseName: arc-runner-set
      valuesObject:
        githubConfigUrl: https://github.com/makeitworkcloud
        githubConfigSecret:
          github_token: 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
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-gha-rs-controller
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  runAsNonRoot: true
                  runAsUser: 1001
                  runAsGroup: 123
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runners-scc-rb
  namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:github-arc
subjects:
- kind: ServiceAccount
  name: arc-runner-set-gha-rs-no-permission
  namespace: arc-runners