---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-system
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    targetRevision: 0.11.0
    helm:
      releaseName: arc-system
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-system