---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: docker-registry
  annotations:
    kustomize.config.k8s.io/behavior: merge
data:
  config.yml: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
        environment: development
    storage:
        delete:
          enabled: true
        cache:
            blobdescriptor: inmemory
        filesystem:
            rootdirectory: /var/lib/registry
        tag:
          concurrencylimit: 5
    http:
        addr: :5000
        debug:
            addr: :5001
            prometheus:
                enabled: true
                path: /metrics
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    proxy:
      remoteurl: ghcr.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/instance: registry
  name: registry
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: registry
  template:
    metadata:
      labels:
        deployment: registry
    spec:
      containers:
      - image: registry
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: 8Gi
          requests:
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-volume
      volumeMounts:
        - mountPath: /etc/distribution/config.yml
          name: registry-config-volume
          subPath: config.yml
      volumes:
        - name: registry-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Gi
        - name: registry-config-volume
          configMap:
            name: docker-registry-config
            items:
              - key: config.yml
                path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
    app.kubernetes.io/component: registry
    app.kubernetes.io/instance: registry
  name: registry
  namespace: docker-registry
spec:
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    deployment: registry